FROM python:3.8

WORKDIR /app

COPY requirements.txt

COPY . /app/.

RUN pip install -r requirements.txt

RUN pip install uwsgi

CMD ["sh", "-c", "python manage.py migrate && uwsgi --http :8000 --module parrotsite.wsgi:application"]
